# Generated by Django 2.2.6 on 2019-10-22 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Version',
            fields=[
                ('version', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('size', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'app_version',
            },
        ),
        migrations.CreateModel(
            name='User_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_img', models.ImageField(default='', height_field='head_height', upload_to='', width_field='head_width')),
                ('head_height', models.PositiveIntegerField(default=200)),
                ('head_width', models.PositiveIntegerField(default=200)),
                ('conf', models.CharField(default='{}', max_length=2300)),
                ('user', models.OneToOneField(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
